### ISSUE TITLE
Is it possibile to upload data to istSOS local from CSV files via internet?

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/istSOS-support#1]
Let`s say a colleague from a University collects temperature logger data in a collaboration project and wants to upload them to our istSOS server.
In such a case she/he probably collects the CSV files from the devices in the field and now has to get them to our server. In such a case it would be useful if the data could be uploaded over the internet.

It was not fully clear to me: is that already possible with the script you wrote? Or would one have to use e.g. a SOS request:
http://istsos.org/en/trunk/doc/ws_insertobservation.html#loading-data-with-ogc-sos-insertobservation-request

**Comment by pesekon2** [comment]
I'm afraid that NINA istSOS is blocked by firewall so it is not possible from outside. But I will take a look at it once more. Anyways, when you are on NINA intranet, it should be possible with the script I wrote (I have successfully uploaded some nonsense data). How, it is described in the documentation [1]. This is just the first (and I think not really good-looking) draft of documentation and will need improvements, but I hope that it's usable for now. 

But now it's working for 1 CSV for each procedure (sensor). To support more sensors in one CSV file, I have to get access to raw sensor data and manage how to do it (and if it's even possible). 

[1] https://github.com/NINAnor/istSOS-support#how-to-use-these-tools

**Comment by ninsbl** [comment]
Thanks for clarification!

Yes, unfortunately, the current installation is behind the firewall. I hope Robert can change that or we can install istSOS at the one existing LINUX web server in NINA.

We might have to discuss data organisation (meaning how to map NINAs project structure with the istSOS concept with services ...).
