### ISSUE TITLE
Separate documentation for users (data manager) and system / server administrator

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/istSOS-support#4]
It is really great that all your tools are accompanied by good documentation.
However, it would be more understandable esp. for people with less technical background if we would separate documentation for system / server administrator (e.g. what is needed to install/run istSOS or how istSOS should be configured (or at  least how you configured it) esp. with regards to security (see also #3) or general data management) and  for users (data managers, researchers that want to add their data). 
Here we should also keep in mind that such users most likely do not have access to the server and scripts there... (Maybe we should have a copy of csv2istsos.py in this repo too (for convenience)?)

BTW: What would you think about putting the documentation into the github wiki?

**Comment by pesekon2** [comment]
+1. I like this idea. 

About csv2istsos.py in this repo: It's an internal istSOS script, so I don't think it's a good idea to copy it here. And it uses some other internal functions and has to be runned from the istSOS folder, so it means that we should copy the whole istSOS folder.

**Comment by ninsbl** [comment]
> It's an internal istSOS script, so I don't think it's a good idea to copy it here. And it uses some other internal functions and has to be runned from the istSOS folder

Given that the data conversion is so deeply integrated into the istSOS code, I would like to encourage you to contact the istSOS devs if your work (different converters) could be interesting for them to get into the main code?

I could imagine that a web form for importing data (possibly with upload of local raw data files) could be a nice enhancement for the data management web interface in istSOS!?

I leave that completely up to you if you want to consider this option...

**Comment by pesekon2** [comment]
> Given that the data conversion is so deeply integrated into the istSOS code, I would like to encourage you to contact the istSOS devs if your work (different converters) could be interesting for them to get into the main code?
> I leave that completely up to you if you want to consider this option...

Yes, we can try it, it sounds good. I would like to make some changes in their csv2istsos and make pull request again, so I can try to ask them after that. 

> I could imagine that a web form for importing data (possibly with upload of local raw data files) could be a nice enhancement for the data management web interface in istSOS!?

Well, it could. But I'm not so deeply familiar with the Tools they're using to create the web Interface. We will see, what do istSOS guys think.
