### ISSUE TITLE
Investigate possibility to add procedures from script

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/istSOS-support#5]
Manually adding hundrets of sensors can be quite time consuming. There is a script for automatizing this part too:
http://istsos.org/en/trunk/doc/ws_registersensor.html#add-other-procedures

Maybe there is a possibility to improve adjust it, so adding procedures becomes more efficient?

**Comment by pesekon2** [comment]
Funny thing is that I'm currently working exactly on this.

**Comment by ninsbl** [comment]
Perfect!
