### ISSUE TITLE
The same database for ninistsos01 and ninsrv16

### ISSUE THREAD

**Issue by pesekon2** [NINAnor/istSOS-support#8]
I have found a little issue. When I was setting up an example service at ninistsos01 and I tried to give it a name templogger as in our service on ninsrv16. When I then removed it from ninistsos01, it was deleted also on ninsrv16 and it has been completely broken. 

The problem is, I think, in the fact that both servers are using the same database. And it can cause problems to us if we want to make one of them as an example and the second one as our real server.

**Comment by ninsbl** [comment]
Added empty "istsos_demo" DB to NINSRV16 with PostGIS extension.
Feel free to use that for the demo and the other one for the "production" instance. 
Please adjust istSOS settings accordingly and close the issue once things work as expected...

**Comment by pesekon2** [comment]
Super, thanks.
